# Generated by Django 5.1.4 on 2025-01-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_remove_player_score_remove_player_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
