# Generated by Django 5.0.4 on 2025-01-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aggregate_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
